### ISSUE TITLE
The current status?

### ISSUE THREAD

**Issue by ihard** [ITECOMMPAY/kibouse#1]
Could you tell me the current status of the project. Did it go beyond the prototype? 
Is there any development?

**Comment by Slach** [comment]
yep, it's really interesting, this project is life?

**Comment by alexey-milovidov** [comment]
I'm also interested.

**Comment by Perlovka** [comment]
+1

**Comment by sgnrslv** [comment]
Hi all.

Development on the project was stoped. 
We decided to stay with elastic as the main logs' storage and hence there is no need for us in kibana for clickhouse.

We still see some potential with this approach though. And hope the community will find our MVP helpful and proceed with this using kibouse as the start point.
